### ISSUE TITLE
do not over-write tags when they exist on applied objects

### ISSUE THREAD

**Issue by govvin** [maripo/JOSM_easypresets#23]
Perhaps, a better behavior than over-writing tags is to append the values to existing tags, and allow the user to edit it, as appropriate. The current behavior that simply overwrites tag, can cause inadvertent information loss.

**Comment by maripo** [comment]
This behavior is dependent on JOSM's functionalities.
For example, when "Pub" is applied to an existing restaurant (amenity=restaurant) node, the existing tag is overwritten with a new tag "amenity=pub".
If you want to allow a user to edit tags, using "Textbox" type instead of "Fixed value" is more appropriate.
